[package]
name = "bevy_web_codecs_gltf"
version = "0.19.0"
edition = "2024"
description = "A fork of bevy_gltf which decodes images using bevy_web_codecs"
repository = "https://github.com/jf908/bevy_web_codecs"
keywords = ["gamedev", "wasm", "bevy"]
license = "MIT OR Apache-2.0"
readme = "README.md"
exclude = ["assets/"]

[features]
pbr_transmission_textures = ["bevy_pbr/pbr_transmission_textures"]
pbr_multi_layer_material_textures = [
  "bevy_pbr/pbr_multi_layer_material_textures",
]
pbr_anisotropy_texture = ["bevy_pbr/pbr_anisotropy_texture"]
pbr_specular_textures = ["bevy_pbr/pbr_specular_textures"]

[dependencies]
# bevy
bevy_animation = { version = "0.19.0", features = ["bevy_mesh"], optional = true }
bevy_app = { version = "0.19.0" }
bevy_asset = { version = "0.19.0" }
bevy_color = { version = "0.19.0" }
bevy_ecs = { version = "0.19.0" }
bevy_image = { version = "0.19.0" }
bevy_light = { version = "0.19.0" }
bevy_camera = { version = "0.19.0" }
bevy_material = { version = "0.19.0" }
bevy_math = { version = "0.19.0" }
bevy_mesh = { version = "0.19.0", features = ["morph", "bevy_mikktspace"] }
bevy_pbr = { version = "0.19.0" }
bevy_reflect = { version = "0.19.0" }
bevy_render = { version = "0.19.0" }
bevy_world_serialization = { version = "0.19.0" }
bevy_transform = { version = "0.19.0" }
bevy_tasks = { version = "0.19.0" }
bevy_platform = { version = "0.19.0", default-features = false, features = [
  "std",
  "serialize",
] }

bevy_web_codecs = { path = "../bevy_web_codecs", version = "0.2" }

# other
gltf = { version = "1.4.0", default-features = false, features = [
  "KHR_lights_punctual",
  "KHR_materials_transmission",
  "KHR_materials_ior",
  "KHR_materials_volume",
  "KHR_materials_unlit",
  "KHR_materials_emissive_strength",
  "KHR_texture_transform",
  "extras",
  "extensions",
  "names",
  "utils",
] }
thiserror = { version = "2", default-features = false }
base64 = "0.22.0"
fixedbitset = "0.5"
itertools = "0.14"
percent-encoding = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
smallvec = { version = "1", default-features = false }
tracing = { version = "0.1", default-features = false, features = ["std"] }


[dev-dependencies]
bevy_log = "0.19.0"
bevy = { version = "0.19.0", default-features = false, features = [
  "std",
  "async_executor",
  "android-game-activity",
  "bevy_animation",
  "bevy_asset",
  "bevy_audio",
  "bevy_color",
  "bevy_core_pipeline",
  "bevy_post_process",
  "bevy_anti_alias",
  "bevy_gilrs",
  "bevy_gizmos",
  # "bevy_gltf",
  "bevy_input_focus",
  "bevy_log",
  "mesh_picking",
  "bevy_pbr",
  "bevy_picking",
  "bevy_render",
  "bevy_scene",
  "bevy_world_serialization",
  "bevy_image",
  "bevy_mesh",
  "bevy_camera",
  "bevy_light",
  "bevy_shader",
  "bevy_sprite",
  "sprite_picking",
  "bevy_sprite_render",
  "bevy_state",
  "bevy_text",
  "bevy_ui",
  "ui_picking",
  "bevy_ui_render",
  "bevy_window",
  "bevy_winit",
  "custom_cursor",
  "default_font",
  "hdr",
  "ktx2",
  "multi_threaded",
  # "png",
  "reflect_auto_register",
  "smaa_luts",
  "sysinfo_plugin",
  "tonemapping_luts",
  "vorbis",
  "webgl2",
  "x11",
  "wayland",
  "debug",
  "zstd_rust",
] }


[lints.clippy]
doc_markdown = "warn"
manual_let_else = "warn"
match_same_arms = "warn"
redundant_closure_for_method_calls = "warn"
redundant_else = "warn"
semicolon_if_nothing_returned = "warn"
type_complexity = "allow"
undocumented_unsafe_blocks = "warn"
unwrap_or_default = "warn"
needless_lifetimes = "allow"
too_many_arguments = "allow"
nonstandard_macro_braces = "warn"
print_stdout = "warn"
print_stderr = "warn"

ptr_as_ptr = "warn"
ptr_cast_constness = "warn"
ref_as_ptr = "warn"

# see: https://github.com/bevyengine/bevy/pull/15375#issuecomment-2366966219
too_long_first_doc_paragraph = "allow"

std_instead_of_core = "warn"
std_instead_of_alloc = "warn"
alloc_instead_of_core = "warn"

allow_attributes = "warn"
allow_attributes_without_reason = "warn"

[lints.rust]
missing_docs = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(docsrs_dep)'] }
unsafe_code = "deny"
unsafe_op_in_unsafe_fn = "warn"
unused_qualifications = "warn"

[package.metadata.docs.rs]
targets = ["wasm32-unknown-unknown"]
all-features = true
